<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Invalid Data</name>
  <uuid>7cea47b2-b1eb-4183-b9c4-79add2295dea</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'Valid Data' is false then 

set decision to "Invalid Data" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
