<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Low Confidence</name>
  <uuid>d914d296-01a1-440c-9998-da94c8c1d8df</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the probability of 'model results' is less than 0.5 then set decision to  "No Advice Possible"   ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
