<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Use Model Results</name>
  <uuid>37e2390b-11da-44b8-b14c-925300841146</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the probability of 'model results'  is more than 0.95 then set decision to the prediction of 'model results'   ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
