<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Output</name>
  <uuid>905d04dd-ae3e-4f88-836c-cd84e049861d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Drug Predictive Model Result where
		the prediction is the prediction of 'ML model invocation', 
	the probability is 1 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
