<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Input</name>
  <uuid>6fb2f294-7dac-48ee-a728-8e1ed556b277</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the age is the age of 'the patient' , 
		the bmi is the bmi of 'the patient' , 
		the bp is the bp of 'the patient' , 
		the gender is the gender of 'the patient' ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
