<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Older Females Low Confidence</name>
  <uuid>5b322014-2ea8-479c-8043-047d65a50212</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if all of the following conditions are true : 
    - the age of 'Patient Details'  is more than 95
    - the gender of 'Patient Details' is "F"  

then
set decision to a new Predictive Model Result where
        the prediction is "Viagra", 
        the probability is 0.45 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
