<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>bc39b144-b256-4460-998f-d289ae2febf2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
