<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Default - P3</name>
  <uuid>5d95c329-975b-466c-bafc-c56ae1fee8d4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "P3" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
