<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Females over 90 High BP - Rules</name>
  <uuid>48346670-eaf7-46af-b066-68fa431183b2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if all of the following conditions are true : 
    - the age of 'the patient' is more than 90
    - the bp of 'the patient' is "H" 
then  
set decision to "Rules" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
