<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Use Rules</name>
  <uuid>de3f5f6b-ee1e-400e-a3f3-299fbb9249b4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Model Selection' is "Rules"
then
set decision to the rule based selection computed from
      Patient Details being 'the patient' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
