<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Use P3</name>
  <uuid>5e0577ef-c36d-44f1-b10f-9afc6539bbc8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the drug P3 XGB computed from
      the patient being <the patient> ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
