<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Use P6</name>
  <uuid>848b99a2-1ddc-4506-8dd2-f446fa5677d0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Model Selection' is "P6"
then
set decision to the drug predictor V2 P6 DT computed from
      Patient Details being 'the patient' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
