<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Values</name>
  <uuid>9268be5b-e940-42bb-ac9c-44a14836e4fc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
        the age is the age of 'Patient Details', 
        the bmi is the bmi of 'Patient Details' , 
        the bp is the bp of 'Patient Details' , 
        the gender is the gender of 'Patient Details'  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
